---

- name: Disable fernet_encrypt_dist_remote_exists and fernet_decrypt_dist_remote_exists
  ansible.builtin.set_fact:
    fernet_encrypt_dist_remote_exists: false
    fernet_decrypt_dist_remote_exists: false

- name: Include verify in remote tasks
  ansible.builtin.include_tasks: verify-remote.yml
  when:
    - fernet_check_dist_remote is defined
    - fernet_check_dist_remote | bool

