---

- name: Verify in remote if exists {{ fernet_encrypt_dist_path }}
  ansible.builtin.stat:
    path: "{{ fernet_encrypt_dist_path }}"
    get_checksum: true
    checksum_algorithm: sha256
  become: false
  register: fernet_encrypt_dist_remote_result
  when:
    - fernet_encrypt_dist_path is defined
    - fernet_encrypt_dist_remote is defined
    - fernet_encrypt_dist_remote | bool

